# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-12-30 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_tesxt',
            new_name='question_text',
        ),
    ]
