# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-21 17:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessionID', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='SessionID')),
                ('clientIP', models.CharField(max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('sessionTimeout', models.IntegerField(default=3600)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_session', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ('created',),
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passwordHash', models.CharField(help_text='<div style="color:red">! This field is set to ensure admin security. Replace it directly with a new password and save it automatically for sha256 encryption.Don\'t repeat by clicking the Save button. </div>', max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user',),
                'verbose_name': 'User-passwordHash',
                'verbose_name_plural': 'Users-passwordHash',
            },
        ),
    ]
