# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-27 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import itm.esmodels


class Migration(migrations.Migration):

    dependencies = [
        ('itm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('anomalyID',),
                'verbose_name': 'Anomaly',
                'verbose_name_plural': 'Anomalies',
            },
            bases=(itm.esmodels.Dict2Obj, models.Model),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('deviceID',),
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
            bases=(itm.esmodels.Dict2Obj, models.Model),
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('parameterID',),
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'Parameters',
            },
            bases=(itm.esmodels.Dict2Obj, models.Model),
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('deviceID',),
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
            bases=(itm.esmodels.Dict2Obj, models.Model),
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('user',), 'verbose_name': 'User password', 'verbose_name_plural': 'Users password'},
        ),
        migrations.AddField(
            model_name='anomaly',
            name='parameterUuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itm.Parameter'),
        ),
    ]
