Document: itpserver
Title: Debian itpserver Manual
Author: <insert document author here>
Abstract: This manual describes what itpserver is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/itpserver/itpserver.sgml.gz

Format: postscript
Files: /usr/share/doc/itpserver/itpserver.ps.gz

Format: text
Files: /usr/share/doc/itpserver/itpserver.text.gz

Format: HTML
Index: /usr/share/doc/itpserver/html/index.html
Files: /usr/share/doc/itpserver/html/*.html
